GET https://app.asana.com/api/1.0/users/me
Authorization: Bearer {{pat}}

###
GET https://app.asana.com/api/1.0/tags
Authorization: Bearer {{pat}}

###
GET https://app.asana.com/api/1.0/tags?opt_fields=name,color,notes,workspace
Authorization: Bearer {{pat}}

