<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://algebra.hr/interop/soap"
           xmlns:s="http://algebra.hr/interop/soap"
           elementFormDefault="qualified">

    <xs:element name="SearchTagsRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="term" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="SearchTagsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="generatedFile" type="xs:string"/>
                <xs:element name="totalInFile" type="xs:int"/>
                <xs:element name="matchCount" type="xs:int"/>
                <xs:element name="tag" type="s:soapTag" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="soapTag">
        <xs:sequence>
            <xs:element name="gid" type="xs:string" minOccurs="0"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="color" type="xs:string" minOccurs="0"/>
            <xs:element name="notes" type="xs:string" minOccurs="0"/>
            <xs:element name="workspaceGid" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>